config/routes.rb
Rails.application.routes.draw do
    root 'users#index'

  resources :users

  resources :churches, shallow: true do
    resources :services, shallow: true do
      resources :rides
    end
  end

  get 'login', to: 'logins#new', as: :login
  post 'login', to: 'logins#create', as: :logins
  delete 'logout', to: 'logins#destroy', as: :logout
    

end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :church, inverse_of: :services
  has_many :rides
  validates :church, presence: true
  validates :start_time, presence: true
  validates :finish_time, presence: true
  validates :day_of_week, presence: true
  validates :location, presence: true
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :ensure_user_logged_in, only: [:edit, :update]
  before_action :ensure_correct_user, only: [:edit, :update]
  
  def index
    order_param = (params[:order] || :Day).to_sym
    case order_param
    when :Day
      @services = Service.all.to_a
      weekorder = {"Sunday" => 1, "Monday" => 2, "Tuesday" => 3, "Wednesday" => 4, "Thursday" => 5, "Friday" => 6, "Saturday" => 7}
      @services.sort! {|a,b| weekorder[a.day_of_week] <=> weekorder[b.day_of_week]}
 # own sort operation
    when :Time
      @services = Service.order(:start_time)
    end
  end
  
  def show
    @service = Service.find(params[:id])
    rescue
      flash[:danger] = "Unable to find service"
      redirect_to services_path
  end
  
  def update
    @service = Service.find(params[:id])
    if @service.update(service_params)
      flash[:success] = "You have modified the service profile"
      redirect_to @service.church
		else
      flash[:danger] = "Unable to update the service profile"
			render 'edit'
		end
  end
  
  def edit
  end
  
  private
  def service_params
    params.require(:service).permit(:start_time,
					                        :finish_time,
					                        :location,
       				                    :day_of_week,
                                  :id )
  end
  
  def ensure_user_logged_in
        unless current_user
            flash[:warning] = "Not logged in"
            redirect_to login_path
        end
    end
  
      def ensure_correct_user
        @service = service.find(params[:id])
        unless current_user?(@service.user)
            flash[:danger] = "Cannot edit other user's profiles"
          redirect_to root_path
	    end
    rescue
	    flash[:danger] = "Unable to find user"
        redirect_to services_path
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_service.html.erb
<li>
    <ul>
	    <li>Locaiton: <%= service.church.name %></li>
      <li>Time: <%= service.day_of_week %> @ <%= service.start_time %></li>
    </ul>
</li>

app/views/services/index.html.erb
<h1>List of services</h1>

<p><%= pluralize(@services.count, 'services') %></p>
<ol><%= render @services %></ol>

app/views/services/show.html.erb
<h1>Service page from Church <%@service.church.name%> </h1>

<p>Location: <%= @service.location %></p>
<p>Day service is held: <%= @service.day_of_week %></p>
<p>Start time: <%= @service.start_time %></p>
<p>Finish time: <%= @service.finish_time %></p>

<% if @service.rides.count >= 1 %>
  <p>Rides avalible</p>
  <ol>
    <% @service.rides.each do |ride| %>
      <div class = "ride<%= ride.id %>" >
        <li><%= ride.date %> </li>
        <li><%= ride.meeting_location %> </li>
        <li><%= link_to "more info", ride_path(ride) %></li>
      </div>
    <%end%>
  </ol>
<% else %>
<p>No rides currently avalible</p>
<% end %>

<% if logged_in? %>
  <%= render 'shared/errors', object: @service %>

<%= form_for [@service, @service.rides.build] do |form| %>
    <%= render partial: "rides/fields", locals: { f: form } %>

    <%= form.submit "Offer ride" %>
  <% end %>
<% end %>