config/routes.rb
Rails.application.routes.draw do
    root 'users#index'

  resources :users

  resources :churches, shallow: true do
    resources :services, shallow: true do
      resources :rides
    end
  end

  get 'login', to: 'logins#new', as: :login
  post 'login', to: 'logins#create', as: :logins
  delete 'logout', to: 'logins#destroy', as: :logout
    

end

app/models/church.rb
class Church < ActiveRecord::Base
  belongs_to :user, inverse_of: :church_managed
  has_many :services, inverse_of: :church
  has_many :users, inverse_of: :church

  accepts_nested_attributes_for :services
  validates :user, presence: true
  validates :name, presence: true
 
end

app/controllers/churches_controller.rb
class ChurchesController < ApplicationController
  before_action :ensure_user_logged_in, only: [:new, :create, :edit, :update, :destroy]
#  before_action :ensure_correct_user, only: [:edit, :update, :destroy]
  before_action :ensure_church_manager, only: [:edit, :update, :destroy]
  
  def index
    @churches = Church.all
  end
  
  def new
    @church = Church.new
    @church.services.build
  end

  def create
    @church = Church.new(church_params)
    @church.user = current_user
    if @church.save
      flash[:success] = "Church created"
      redirect_to @church
    else
      flash.now[:danger] = "Unable to create church"
      render 'new'
    end
  end
  
  def show
    @church = Church.find(params[:id])
    rescue
		  flash[:danger] = "Unable to find church"
      redirect_to churches_path
  end
  
  def edit
  end
  
  def update
		@church = Church.find(params[:id])
    if @church.update(church_params)
      flash[:success] = "You have modified the church profile"
			redirect_to @church
		else
      flash[:danger] = "Unable to update the church profile"
			render 'edit'
		end
#  rescue
#    flash[:warning] = "Please login"
#		  redirect_to churches_path
	end
  
  def destroy
    @church = Church.find(params[:id])
    @church.destroy
    flash[:success] = "#{@church.name} removed"
    redirect_to churches_path
  end
  
  private

  def church_params
	  params.require(:church).permit(:name,
		                           :web_site,
		                           :description,
		                           :picture,
				       services_attributes: [ :start_time,
					                        :finish_time,
					                        :location,
       				                    :day_of_week,
                                  :id] )
    end
  
  def ensure_church_manager
    @church = Church.find(params[:id])
    unless current_user?(@church.user) || current_user.admin?
      flash[:danger] = "Only church manager can edit church profile"
      redirect_to root_path
    end
    rescue
    flash[:danger] = "Unable to find church"
      redirect_to churches_path
  end
    

  
#  def ensure_correct_user
#	  @user = User.find(params[:id])
#	  unless current_user?(@user)
#     flash[:warning] = "Cannot edit other user's church profiles"
#      redirect_to @church
#	  end
#    rescue
#	    flash[:warning] = "Unable to find user"
#	    redirect_to users_path
#  end
  
    def ensure_user_logged_in
    unless current_user
      flash[:warning] = "Not logged in, please Sign In"
      redirect_to login_path
    end
  end
  
end

app/helpers/churches_helper.rb
module ChurchesHelper
end

app/views/churches/_church.html.erb
<li>
    <ul>
	    <li>Name: <%= church.name %>
        <%= link_to "delete", church, method: :delete %></li>
      <li><%= link_to 'Church details', church %></li>
    </ul>
</li>

app/views/churches/_fields.html.erb
<p><%= f.label :name, 'Church Name:' %>
  <%= f.text_field :name %></p>

<p><%= f.label :web_site %>:
<%= f.text_field :web_site %></p>

<p><%= f.label :picture %>:
<%= f.text_field :picture %></p>

<p><%= f.label :description %>:
<%= f.text_area :description %></p>

<%= f.fields_for :services do |builder| %>
    <p><%= builder.label :start_time %>:
    <%= builder.text_field :start_time %></p>

    <p><%= builder.label :finish_time %>:
    <%= builder.text_field :finish_time %></p>

    <p><%= builder.label :location %>:
    <%= builder.text_field :location %></p>

    <p><%= builder.label :day_of_week %>:
    <%= builder.text_field :day_of_week %></p>
<% end %>

app/views/churches/edit.html.erb
<h1>Edit church profile</h1>

<%= render 'shared/errors', object: @church %>

<%= form_for @church do |form| %>
  <%= render partial: "fields", locals: { f: form } %>

	<%= form.submit "Update church profile" %>
<% end %>

app/views/churches/index.html.erb
<h1>List of churches</h1>

<p> <%= pluralize(@churches.count, 'church') %></p>
<ol><%= render @churches %></ol>

app/views/churches/new.html.erb
<%= render 'shared/errors', object: @church %>

<%= form_for @church do |form| %>
  <%= render partial: 'fields', locals: { f: form } %>

  <%= form.submit "Create new church" %>
<% end %>

app/views/churches/show.html.erb
<h1>Church Page for <%= @church.name %></h1>

<p> <img><%= @church.picture %></img> </p>
<p>Link: <%= link_to 'official web site', @church.web_site %></p>
<p>Church Description: <%= @church.description %> </p>

<% if logged_in? %>
<%= button_to "Attend this church", user_path(current_user, church_id: @church.id), { method: :patch} %>

<%end%>

<ol>
  <% @church.services.each do |services| %>
    <div class = "service<%= services.id %>" >
      <li><%= link_to "Service Page", service_path(services) %> </li>    
      <ul>
        <li>Location:<%=services.location%></li>
        <li>Day of Week: <%= services.day_of_week %> </li>
        <li>Start time: <%= services.start_time %> </li>
        <li>Finish time: <%= services.finish_time %> </li>
      </ul>
  </div>
  <%end%>
</ol>


<p>Attendees List</p>
<ol>
  <% @church.users.each do |attendees| %>
    <div class = "user<%= attendees.id %>" >
      <li><%= link_to attendees.name, user_path(attendees) %></li> 
    </div>
  <%end%>
</ol>